/* AUTO-GENERATED from measurement-spec.json by scripts/sync_measurement_spec.py. */
/* Do not edit this file directly. */
(function (root, factory) {
  const api = factory();
  if (typeof module === "object" && module.exports) module.exports = api;
  root.FrescoMeasurement = api;
})(typeof globalThis !== "undefined" ? globalThis : this, function () {
  "use strict";
  const SPEC = Object.freeze({"airDensityKgM3":1.2,"ballDiameterM":0.057,"ballMassKg":0.04,"defaultCourtLengthM":7.0,"dragCoefficient":0.5,"model":"quadratic-drag-distance","nearMicrophone":{"correction":"For a near-to-far pair subtract distance/soundSpeed from observed interval; for a far-to-near pair add it.","definition":"firstOnsetSide is the side of onset index 0 relative to the microphone.","firstOnsetSideRequired":true},"qualityGate":{"maxFlightSeconds":0.9,"maxInitialSpeedKmh":110.0,"minFlightSeconds":0.2},"schemaVersion":1,"soundSpeedMps":343.0,"version":"2026-07-10"});

  function positiveNumber(value, name) {
    const n = Number(value);
    if (!Number.isFinite(n) || n <= 0) throw new RangeError(name + " must be a positive number");
    return n;
  }

  function dragPerMetre() {
    const area = Math.PI * Math.pow(SPEC.ballDiameterM / 2, 2);
    return SPEC.airDensityKgM3 * SPEC.dragCoefficient * area / (2 * SPEC.ballMassKg);
  }

  function theoreticalInitialFactor(lengthM) {
    const length = positiveNumber(lengthM == null ? SPEC.defaultCourtLengthM : lengthM, "lengthM");
    const kL = dragPerMetre() * length;
    return Math.expm1(kL) / kL;
  }

  function resolveInitialFactor(lengthM, calibrationFactor) {
    if (calibrationFactor !== undefined && calibrationFactor !== null && calibrationFactor !== "") {
      return positiveNumber(calibrationFactor, "calibrationFactor");
    }
    return theoreticalInitialFactor(lengthM);
  }

  function correctedFlightTime(observedSeconds, pairStartIndex, micPosition, firstOnsetSide, lengthM) {
    const observed = positiveNumber(observedSeconds, "observedSeconds");
    if (micPosition !== "near") return observed;
    const pairIndex = Number(pairStartIndex);
    if (!Number.isInteger(pairIndex) || pairIndex < 0) throw new RangeError("pairStartIndex must be a non-negative integer");
    if (firstOnsetSide !== "near" && firstOnsetSide !== "far") throw new RangeError("firstOnsetSide must be near or far");
    const length = positiveNumber(lengthM == null ? SPEC.defaultCourtLengthM : lengthM, "lengthM");
    const startsNear = pairIndex % 2 === 0 ? firstOnsetSide === "near" : firstOnsetSide === "far";
    const propagationDelay = length / SPEC.soundSpeedMps;
    return observed + (startsNear ? -propagationDelay : propagationDelay);
  }

  function measureInterval(options) {
    const opts = options || {};
    const lengthM = positiveNumber(opts.lengthM == null ? SPEC.defaultCourtLengthM : opts.lengthM, "lengthM");
    const observedSeconds = positiveNumber(opts.observedSeconds, "observedSeconds");
    const pairStartIndex = opts.pairStartIndex == null ? 0 : opts.pairStartIndex;
    const flightSeconds = correctedFlightTime(observedSeconds, pairStartIndex, opts.micPosition || "center", opts.firstOnsetSide || "near", lengthM);
    const minFlightSeconds = positiveNumber(opts.minFlightSeconds == null ? SPEC.qualityGate.minFlightSeconds : opts.minFlightSeconds, "minFlightSeconds");
    const maxFlightSeconds = positiveNumber(opts.maxFlightSeconds == null ? SPEC.qualityGate.maxFlightSeconds : opts.maxFlightSeconds, "maxFlightSeconds");
    const maxInitialSpeedKmh = positiveNumber(opts.maxInitialSpeedKmh == null ? SPEC.qualityGate.maxInitialSpeedKmh : opts.maxInitialSpeedKmh, "maxInitialSpeedKmh");
    const base = { observedSeconds, flightSeconds, propagationCorrectionSeconds: flightSeconds - observedSeconds };
    if (minFlightSeconds > maxFlightSeconds) throw new RangeError("minFlightSeconds must not exceed maxFlightSeconds");
    if (flightSeconds < minFlightSeconds || flightSeconds > maxFlightSeconds) return Object.assign(base, { accepted: false, reason: "flight_time_out_of_range" });
    const averageSpeedKmh = lengthM / flightSeconds * 3.6;
    const initialSpeedKmh = averageSpeedKmh * resolveInitialFactor(lengthM, opts.calibrationFactor);
    if (initialSpeedKmh > maxInitialSpeedKmh) return Object.assign(base, { accepted: false, reason: "initial_speed_above_trust_limit", averageSpeedKmh, initialSpeedKmh });
    return Object.assign(base, { accepted: true, averageSpeedKmh, initialSpeedKmh });
  }

  return Object.freeze({ spec: SPEC, dragPerMetre, theoreticalInitialFactor, resolveInitialFactor, correctedFlightTime, measureInterval });
});
