'use strict';
const assert=require('assert'),B=require('../ball-tracker.js');
const regions=[{x:0,y:0,w:200,h:300},{x:800,y:0,w:200,h:300}];
const sequence=Array.from({length:8},(_,i)=>({t:i*.03,ballCandidates:[{x:250+i*25,y:100},{x:700+i,y:170}]}));
const base=B.track(sequence,1000,regions);assert.equal(base.length,1);assert.equal(base[0].observedCount,8);
assert.equal(B.at(base,.09).point.kind,'observed');assert.equal(B.at(base,.095).predicted,true);
const gaps=sequence.map((f,i)=>({...f,ballCandidates:i===3?[]:f.ballCandidates}));
const joined=B.track(gaps,1000,regions);assert.equal(joined.length,1);assert.equal(B.at(joined,.09).point.kind,'interpolated');
assert.equal(B.at(joined,.09).point.x,325);assert.equal(joined[0].interpolatedCount,1);
assert.equal(B.at(joined,.3),null,'no extrapolation after last observation');
const long=[...sequence.slice(0,4),...sequence.slice(4).map(f=>({...f,t:f.t+.3}))];
const separated=B.track(long,1000,regions);assert.equal(separated.length,2);assert.equal(B.at(separated,.2),null);
const reverse=[...sequence,...Array.from({length:7},(_,i)=>({t:(8+i)*.03,ballCandidates:[{x:400-i*25,y:100}]}))];
const turns=B.track(reverse,1000,regions);assert(turns.length>=2);assert(turns.every(tr=>tr.points.every((p,i,a)=>!i||Math.sign(p.x-a[i-1].x)===Math.sign(a.at(-1).x-a[0].x))),'do not interpolate across a racket reversal');
assert.equal(B.track(sequence,1000,[]).length,0);
assert.throws(()=>B.track([sequence[1],sequence[0]],1000,regions));
console.log('Ball tracker short-gap interpolation, no long-gap extrapolation, reversal splitting and noise rejection passed');
const nearHand=sequence.map((f,i)=>({...f,poses:i===7?[Array.from({length:33},(_,k)=>k===15?{x:425,y:100,visibility:.45,presence:.9}:null)]:[]}));
const noHand=B.track(nearHand,1000,regions);assert.equal(B.at(noHand,.21),null,'do not attach the final point to a partially visible wrist');
console.log('Hand-proximity rejection passed');
