'use strict';
const assert=require('assert'),fs=require('fs'),vm=require('vm'),S=require('../shot-analysis');
const hits=Array.from({length:28},(_,i)=>({t:i*.5,player:i%2?'b':'a'})),before=JSON.stringify(hits);
const fallback=S.simpleRoles(hits);assert.equal(fallback.filter(e=>e.player==='a'&&e.type==='attack').length,14);assert.equal(fallback.filter(e=>e.player==='b'&&e.type==='defense').length,14);
assert(fallback.every(e=>e.provisional));assert.equal(JSON.stringify(hits),before);
const anchored=S.simpleRoles(hits,[{t:2,player:'a',type:'defense',basis:'manual'},{t:10,player:'a',type:'defense',basis:'pose'}]);assert(anchored.every(e=>e.type===(e.player==='a'?'defense':'attack')));assert.equal(anchored[4].basis,'manual');
const swapped=S.simpleRoles(hits,[{t:0,player:'a',type:'attack'},{t:10,player:'a',type:'defense'}]);assert.equal(swapped[0].type,'attack');assert.equal(swapped[26].type,'defense');
assert.deepEqual(S.simpleRoles([]),[]);assert.equal(S.simpleRoles([{t:0,player:'b'}])[0].type,'attack');
const html=fs.readFileSync(require.resolve('../index.html'),'utf8');
assert(!html.includes('id="ulAAttack"'),'A/D counters are no longer part of the UI');
assert(!html.includes('FrescoShots.classify('),'automatic role analysis is not invoked by the UI');
console.log('Legacy role helper remains isolated; no A/D UI or classification invocation');
