'use strict';const assert=require('assert'),S=require('../shot-analysis');
function pose(x){const p=Array.from({length:33},()=>({x:0,y:0,visibility:0}));for(const [i,a,b]of [[11,80,50],[12,120,50],[23,85,120],[24,115,120],[15,100,80],[16,x,80]])p[i]={x:a,y:b,visibility:1,presence:1};return p;}
function frames(x){return [{t:.9,poses:[pose(x-5),[]]},{t:1,poses:[pose(x),[]]},{t:1.1,poses:[pose(x+5),[]]}];}
const e=[{id:'1',t:1,status:'auto',player:'a'}];assert.equal(S.classify(e,frames(155))[0].type,'attack');assert.equal(S.classify(e,frames(108))[0].type,'defense');assert.equal(S.classify(e,frames(125))[0].type,null);assert.equal(S.classify(e,[])[0].type,null);assert.equal(S.classify([{...e[0],shotOverride:'defense'}],[])[0].type,'defense');assert.equal(S.classify([{...e[0],status:'pending'}],frames(155)).length,0);assert.equal(S.summary(S.classify(e,frames(155))).attack,1);
console.log('Shot style estimates: exterior/front, uncertain boundaries, absent poses and manual overrides passed');
const sequence=[{t:.5,status:'confirmed',player:'a'},{t:1,status:'pending',origin:'audio'},{t:1.5,status:'confirmed',player:'a'}];
const alternating=frames(155).map(f=>({...f,poses:[[],f.poses[0]]}));
assert.equal(S.inferAlternation(sequence,alternating,1000)[1].player,'b');
assert.equal(S.inferAlternation(sequence,[],1000)[1].status,'pending');
assert.equal(S.inferAlternation(sequence.map((e,i)=>i===1?{...e,origin:'manual-review'}:e),alternating,1000)[1].status,'pending');
assert.equal(S.inferAlternation(sequence.map((e,i)=>i===2?{...e,player:'b'}:e),alternating,1000)[1].status,'pending');
console.log('Alternation fills a single rhythm-consistent gap only with wrist evidence, preserving manual uncertainty');
const item=(t,player,type,basis='body-wrist-position-v1')=>({t,player,type,basis});
let roles=S.resolveRoles([item(0,'a','attack'),item(.5,'b',null),item(1,'a','attack'),item(1.5,'b','defense')]);
assert.deepEqual(roles.map(e=>e.type),['attack','defense','attack','defense']);
assert(roles.every(e=>e.roles.a!==e.roles.b));
roles=S.resolveRoles([item(0,'a','attack'),item(.5,'b','defense'),item(1,'a','defense'),item(1.5,'b','attack'),item(2,'a','defense')]);
assert.deepEqual(roles.map(e=>e.type),['attack','defense','defense','attack','defense'],'roles switch on sustained opposite posture evidence');
roles=S.resolveRoles([item(0,'a','attack'),item(.5,'b','defense'),item(1,'a','defense'),item(1.5,'b','defense'),item(2,'a','attack')]);
assert.equal(roles[2].type,'attack','single noisy posture does not flip pair roles');
assert.equal(S.resolveRoles([item(0,'a','attack'),item(.5,'b','attack','manual')])[1].type,'attack','manual correction is authoritative');
assert.equal(S.resolveRoles([item(0,'a','attack'),item(4,'b',null)])[1].type,null,'roles do not cross rally gaps');
assert.equal(S.resolveRoles([item(0,'a','attack'),{...item(.5,'b',null),roleBreak:true}])[1].type,null,'pending events break propagation');
assert(S.resolveRoles([item(0,'a',null),item(.5,'b',null)]).every(e=>e.type==null),'no evidence does not invent a role');
assert.equal(S.classify(e,frames(45))[0].type,'defense','cross-body right wrist is not an exterior attack');
const mirrored=frames(155).map(f=>({...f,poses:f.poses.map(ps=>ps.map(p=>({...p,x:200-p.x})))}));
assert.equal(S.classify(e,mirrored)[0].type,'attack','anatomical shoulder side works with mirrored video');
assert.equal(S.summary(roles).byPlayer.a.attack,3);
console.log('Complementary player roles, mid-rally swaps, manual corrections, cross-body and mirrored strokes passed');
const bothHands=x=>frames(x).map(f=>{const p=f.poses[0];p[15]={...p[16],x:p[16].x-4};return f;});
assert.equal(S.classify(e,bothHands(155))[0].type,'attack');
assert.equal(S.classify(e,bothHands(108))[0].type,'defense');
assert.equal(S.classify(e,bothHands(155))[0].hand,'both');
console.log('Two-handed outside strokes are attack; two-handed front strokes are defense');
