'use strict';
const assert = require('assert');
const Q = require('../video-quality.js');
const series = speeds => speeds.map((speed, i) => ({t: i * .4, speed, player: i % 2 ? 'b' : 'a', rNow: i + 1}));
const baseline = [60,61,59,60,105,61,60,59,61];
const input = series(baseline), snapshot = JSON.stringify(input);
const reviewed = Q.review(input);
assert.equal(reviewed.excluded, 1);
assert.equal(reviewed.candidates.length, 1);
assert.equal(reviewed.hits[4].speed, null);
assert.equal(reviewed.hits[4].originalSpeed, 105);
assert.equal(reviewed.hits[4].qualityCode, 'isolated_spike');
assert.equal(JSON.stringify(input), snapshot, 'must not mutate input');
assert.equal(reviewed.hits[4].player, input[4].player);
assert.equal(reviewed.hits[4].rNow, input[4].rNow);
assert.equal(Q.review(reviewed.hits, {autoOutliers:false}).hits[4].speed, 105, 'automatic review must be reversible');
assert.equal(Q.review(reviewed.hits, {overrides:{'1.6':'keep'}}).hits[4].speed, 105);
assert.equal(Q.review(input, {overrides:{'0.8':'drop'}}).hits[2].qualityCode, 'manual');
const limited = Q.review(series([70,80,90]), {maxSpeedKmh:80});
assert.equal(limited.excluded, 1);assert.equal(limited.hits[1].speed, 80);
assert.equal(limited.hits[2].qualityCode, 'above_limit');
assert.equal(Q.review(limited.hits, {maxSpeedKmh:100}).hits[2].speed, 90);
assert.equal(Q.review(limited.hits, {maxSpeedKmh:80,overrides:{'0.8':'keep'}}).hits[2].speed, 90);
assert.equal(Q.review(series([60,60,105,60,60])).candidates.length, 0, 'insufficient context');
assert.equal(Q.review(series([105,60,60,60,60,60,60])).candidates.length, 0, 'edge values need more context');
assert.equal(Q.review(series([60,61,60,60,105,107,60,61,60,60])).excluded, 0, 'adjacent fast shots are preserved');
assert.equal(Q.review(series([105,106,107,108,109,110,111,112,113])).excluded, 0, 'sustained fast rally preserved');
assert.equal(Q.review(series([40,41,39,40,80,41,40,39,40])).excluded, 1, 'not a hardcoded 105 km/h cutoff');
assert.equal(Q.review(series([60,90,50,85,105,45,90,65,90])).excluded, 0, 'high variation requires conservative review');
const gaps = series(baseline).map((h,i)=>({...h,t:i*4}));
assert.equal(Q.review(gaps).excluded, 0, 'do not connect separate rallies');
const absent = Q.review([{t:0,speed:null}], {overrides:{'0':'keep'}});
assert.equal(absent.hits[0].speed, null);assert.equal(absent.excluded, 0);
assert.equal(Q.review(absent.hits).hits[0].originalSpeed, null);
for (const limit of [0,-1,'',NaN,Infinity,true,[80]]) assert.throws(()=>Q.review(input, {maxSpeedKmh:limit}));
assert.throws(()=>Q.review([{t:NaN,speed:60}]));
console.log('Video quality isolation, reversibility, user limits and manual overrides passed');

const wholeVideo=series(Array.from({length:28},(_,i)=>40+(i%7)*5).concat(105));
const globalResult=Q.review(wholeVideo);
assert.equal(globalResult.hits.at(-1).speed,null,'whole-video distribution covers an isolated clip-edge peak');
assert.equal(globalResult.hits.at(-1).qualityCode,'global_isolated_spike');
assert.equal(globalResult.hits.at(-1).originalSpeed,105);
assert.match(globalResult.hits.at(-1).qualityReason,/動画全体/);
const supported=series(Array(30).fill(60));supported[0].speed=80;supported[25].speed=90;supported[12].speed=100;
assert.equal(Q.review(supported).hits[12].speed,100,'repeated 80/90 elsewhere support a local 100 peak');
assert.equal(Q.review(supported).hits[12].isOutlierCandidate,false);
const tooFew=series(Array(18).fill(55).concat(105));
assert.equal(Q.review(tooFew).hits.at(-1).speed,105,'global rule requires at least 20 usable samples');
const consecutive=series(Array(30).fill(55));consecutive[12].speed=105;consecutive[13].speed=110;
assert.equal(Q.review(consecutive).hits[12].speed,105);assert.equal(Q.review(consecutive).hits[13].speed,110);
const lastKey=String(wholeVideo.at(-1).t);
assert.equal(Q.review(globalResult.hits,{overrides:{[lastKey]:'keep'}}).hits.at(-1).speed,105);
assert.equal(Q.review(globalResult.hits,{autoOutliers:false}).hits.at(-1).speed,105);
assert.equal(Q.review(supported,{maxSpeedKmh:95}).hits[12].qualityCode,'above_limit','distribution support does not override explicit caps');
console.log('Whole-video isolated peaks, repeated upper-range support, minimum sample count and reversibility passed');
