#!/usr/bin/env python3
"""Generate the browser copy of the canonical measurement specification.

`measurement-spec.json` is the source of truth.  Python reads it directly and
the browser loads the generated UMD file, so a static PWA can work offline.
Run with --check in CI/tests to catch an accidental divergence.
"""
from __future__ import annotations

import argparse
import json
from pathlib import Path
import sys


ROOT = Path(__file__).resolve().parent.parent
SPEC_PATH = ROOT / "measurement-spec.json"
OUT_PATH = ROOT / "measurement-spec.js"


def render(spec: dict) -> str:
    payload = json.dumps(spec, ensure_ascii=False, sort_keys=True, separators=(",", ":"))
    return f'''/* AUTO-GENERATED from measurement-spec.json by scripts/sync_measurement_spec.py. */
/* Do not edit this file directly. */
(function (root, factory) {{
  const api = factory();
  if (typeof module === "object" && module.exports) module.exports = api;
  root.FrescoMeasurement = api;
}})(typeof globalThis !== "undefined" ? globalThis : this, function () {{
  "use strict";
  const SPEC = Object.freeze({payload});

  function positiveNumber(value, name) {{
    const n = Number(value);
    if (!Number.isFinite(n) || n <= 0) throw new RangeError(name + " must be a positive number");
    return n;
  }}

  function dragPerMetre() {{
    const area = Math.PI * Math.pow(SPEC.ballDiameterM / 2, 2);
    return SPEC.airDensityKgM3 * SPEC.dragCoefficient * area / (2 * SPEC.ballMassKg);
  }}

  function theoreticalInitialFactor(lengthM) {{
    const length = positiveNumber(lengthM == null ? SPEC.defaultCourtLengthM : lengthM, "lengthM");
    const kL = dragPerMetre() * length;
    return Math.expm1(kL) / kL;
  }}

  function resolveInitialFactor(lengthM, calibrationFactor) {{
    if (calibrationFactor !== undefined && calibrationFactor !== null && calibrationFactor !== "") {{
      return positiveNumber(calibrationFactor, "calibrationFactor");
    }}
    return theoreticalInitialFactor(lengthM);
  }}

  function correctedFlightTime(observedSeconds, pairStartIndex, micPosition, firstOnsetSide, lengthM) {{
    const observed = positiveNumber(observedSeconds, "observedSeconds");
    if (micPosition !== "near") return observed;
    const pairIndex = Number(pairStartIndex);
    if (!Number.isInteger(pairIndex) || pairIndex < 0) throw new RangeError("pairStartIndex must be a non-negative integer");
    if (firstOnsetSide !== "near" && firstOnsetSide !== "far") throw new RangeError("firstOnsetSide must be near or far");
    const length = positiveNumber(lengthM == null ? SPEC.defaultCourtLengthM : lengthM, "lengthM");
    const startsNear = pairIndex % 2 === 0 ? firstOnsetSide === "near" : firstOnsetSide === "far";
    const propagationDelay = length / SPEC.soundSpeedMps;
    return observed + (startsNear ? -propagationDelay : propagationDelay);
  }}

  function measureInterval(options) {{
    const opts = options || {{}};
    const lengthM = positiveNumber(opts.lengthM == null ? SPEC.defaultCourtLengthM : opts.lengthM, "lengthM");
    const observedSeconds = positiveNumber(opts.observedSeconds, "observedSeconds");
    const pairStartIndex = opts.pairStartIndex == null ? 0 : opts.pairStartIndex;
    const flightSeconds = correctedFlightTime(observedSeconds, pairStartIndex, opts.micPosition || "center", opts.firstOnsetSide || "near", lengthM);
    const minFlightSeconds = positiveNumber(opts.minFlightSeconds == null ? SPEC.qualityGate.minFlightSeconds : opts.minFlightSeconds, "minFlightSeconds");
    const maxFlightSeconds = positiveNumber(opts.maxFlightSeconds == null ? SPEC.qualityGate.maxFlightSeconds : opts.maxFlightSeconds, "maxFlightSeconds");
    const maxInitialSpeedKmh = positiveNumber(opts.maxInitialSpeedKmh == null ? SPEC.qualityGate.maxInitialSpeedKmh : opts.maxInitialSpeedKmh, "maxInitialSpeedKmh");
    const base = {{ observedSeconds, flightSeconds, propagationCorrectionSeconds: flightSeconds - observedSeconds }};
    if (minFlightSeconds > maxFlightSeconds) throw new RangeError("minFlightSeconds must not exceed maxFlightSeconds");
    if (flightSeconds < minFlightSeconds || flightSeconds > maxFlightSeconds) return Object.assign(base, {{ accepted: false, reason: "flight_time_out_of_range" }});
    const averageSpeedKmh = lengthM / flightSeconds * 3.6;
    const initialSpeedKmh = averageSpeedKmh * resolveInitialFactor(lengthM, opts.calibrationFactor);
    if (initialSpeedKmh > maxInitialSpeedKmh) return Object.assign(base, {{ accepted: false, reason: "initial_speed_above_trust_limit", averageSpeedKmh, initialSpeedKmh }});
    return Object.assign(base, {{ accepted: true, averageSpeedKmh, initialSpeedKmh }});
  }}

  return Object.freeze({{ spec: SPEC, dragPerMetre, theoreticalInitialFactor, resolveInitialFactor, correctedFlightTime, measureInterval }});
}});
'''


def main() -> int:
    parser = argparse.ArgumentParser(description="ブラウザ用の計測仕様を生成・検査します")
    parser.add_argument("--check", action="store_true", help="生成物が最新なら0、差分があれば1")
    args = parser.parse_args()
    spec = json.loads(SPEC_PATH.read_text(encoding="utf-8"))
    rendered = render(spec)
    if args.check:
        current = OUT_PATH.read_text(encoding="utf-8") if OUT_PATH.exists() else ""
        if current != rendered:
            print("measurement-spec.js is out of date; run scripts/sync_measurement_spec.py", file=sys.stderr)
            return 1
        return 0
    OUT_PATH.write_text(rendered, encoding="utf-8")
    print(f"generated {OUT_PATH.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
